---
title: "Test yourself 05"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


Rate your confidence of being able to answer the below questions saying A, B or C, where:

- A. I am confident that I know the answer to this question
- B. I know at least 50% of the answer to this question, within 20 minutes I could find the required resources to enable a complete answer
- C. I am not confident that I can answer the question at this time.


### Part I

1. Could you name the method where  cells are repeatedly split up into wells, labeled with part of a barcode and pooled again?
2. Could you tell what is the most common number in a scATAC-seq count matrix?
3. Could you explain what was the problem with the early single cell ChIP-seq methods?
4. Could you tell which data types from the same cells one can measure with 10X Genomics methods?
5. Could you tell what anchors are used in the data integration method by Seurat?
6. Could you explain why unsupervised methods are useful when thinking of today's materials?
7. Could you explain what “reduce(peaks + 100)” command do when using GRanges package in R?
8. Could you explain what the gene activity scores are based on in Seurat? 

### Part II

1. What is the method called where cells are repeatedly split up into wells, labeled with part of a barcode and pooled again?
a) Drop-seq
b) single-cell combinatorial-indexing
c) SMART
d) SCRAM
	
2. What is the most common number in a scATAC-seq count matrix?
a) 0
b) 1
c) 2
d) 3
	
3. What was the problem with the early single cell ChIP-seq methods?
a) Too much noise in repeat regions
b) Too many reads that would not align to the genome
c) Too much starting material required
d) Too few reads per cell
	
4. There is a nice new single cell method from 10X Genomics available, where you can measure several types of data from the same cells. Which data?
a) RNA and TF binding
b) TF binding and DNA methylation
c) DNA methylation and open chromatin
d) open chromatin and RNA

5. What are anchors in the data integration method used by Seurat?
a) Clusters of cells
b) Pairs of similar cells from the same data set
c) Pairs of similar genes, from the same data set
d) Pairs of cells, from different data sets, that are mutual nearest neighbors

6. Why are unsupervised methods useful?
a) Because they are fast
b) Because they can show you unexpected patterns in data
c) Because they can handle large data sets
d) Because they can handle missing values

7. What does the command “reduce(peaks + 100)” do when you use the GRanges package in R?
a) Select the top 100 peaks, and select all peaks that don’t overlap with any other peak
b) Add 100 random peaks, and collapse all overlapping peaks
c) Extend all peaks 100 bp in each direction, and collapse all overlapping peaks
d) Shift all peaks 100 bp, and select all peaks that don’t overlap with any other peak

8. What are the gene activity scores Seurat calculates based on?
a) ATAC-seq reads in the promoter regions of each gene
b) Gene expression variability
c) The fraction of reads in peak in each cell
d) The number of cells in each cell type