---
title: "Friday morning session"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


## Welcome to Friday! Almost there...

In your group discuss:

- yesterday's questions (below); can you agree on the answers?
- anything that you've found confusing or useful yesterday
- and post your answers and comments on our [whiteboard](https://jamboard.google.com/d/1PSY_jTxLy26TsIFbmxnOLe-tP8LOSsK-AzES-ihx4qo/edit?usp=sharing)


-----

**Thursday's questions**

1. Why should you use a workflow manager for your analysis instead of manually running tools?
a) More accurate results
b) Better documentation of results
c) To avoid accidental mistakes
d) Better reproducibility / portability of analysis

2. What is the difference between single hyphens and double hyphens in a Nextflow command?
a) There is no difference
b) Single hyphens denote core Nextflow options, double are pipeline parameters
c) Double hyphens denote core Nextflow options, single are pipeline parameters
d) Depends on the pipeline

3. Which two commands are useful for re-running a failed pipeline?
a) nextflow pull
b) nextflow log
c) nextflow run -name
d) nextflow run -resume

4. Which peak caller does the nf-core/chipseq pipeline use?
a) MACS2
b) Genrich
c) SEACR
d) All of the above

5. What was the name given to the new, modular language implemented within Nextflow
a) Nextflow 2.0
b) Nextflow modules
c) DSL2
d) nf-core/modules

6. Which QC metric is not generated by the nf-core/chipseq pipeline?
a) Strand cross-correlation plots
b) Normalized strand coefficient & Relative strand correlation ratios
c) TSS enrichment plots
d) Gene count suitability plots

7. Why does the nf-core/atacseq pipeline merge peaks sets across technical and biological replicates?
a) To find a consensus set of peaks for downstream analysis
b) To get give the best genome coverage possible
c) To reduce background noise in the data
d) To make the pipeline run faster

8. Why are mitochondrial reads removed in the nf-core/atacseq pipeline?
a) To get a better idea of the genome-wide duplication rate
b) To avoid bias in downstream analysis
c) Because some tissues and cell types can give libraries with a large fraction of mito reads
d) All of the above