---
title: "Questions 04"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


1. Could you explain why you should use a workflow manager for the analysis instead of manually running tools?
2. Could you explain a difference between single hypens and double hyphens in a Nextflow command?
3. Could you identify the command for re-running a failed pipeline?
4. Could you explain how peak calling is run in the nf-core/chipseq pipeline?
5. Could you name the modular languagte implemetned within Nextflow?
6. Could you explain which QC metrics are generated by the nf-core/chipseq pipeline?
7. Could you explain why the nf-core/atacseq pipeline merges peaks sets across technical and biological replicates?
8. Could you explain why mitochondrial reads are removed in the nf-core/atacseq pipeline?

1. Why should you use a workflow manager for your analysis instead of manually running tools?
a) More accurate results
b) Better documentation of results
c) To avoid accidental mistakes
d) Better reproducibility / portability of analysis (CORRECT)

2. What is the difference between single hyphens and double hyphens in a Nextflow command?
a) There is no difference
b) Single hyphens denote core Nextflow options, double are pipeline parameters (CORRECT)
c) Double hyphens denote core Nextflow options, single are pipeline parameters
d) Depends on the pipeline

3. Which two commands are useful for re-running a failed pipeline?
a) nextflow pull
b) nextflow log (CORRECT)
c) nextflow run -name
d) nextflow run -resume (CORRECT)

4. Which peak caller does the nf-core/chipseq pipeline use?
a) MACS2 (CORRECT)
b) Genrich
c) SEACR
d) All of the above

5. What was the name given to the new, modular language implemented within Nextflow
a) Nextflow 2.0
b) Nextflow modules
c) DSL2 (CORRECT)
d) nf-core/modules

6. Which QC metric is not generated by the nf-core/chipseq pipeline?
a) Strand cross-correlation plots
b) Normalized strand coefficient & Relative strand correlation ratios
c) TSS enrichment plots
d) Gene count suitability plots (CORRECT)

7. Why does the nf-core/atacseq pipeline merge peaks sets across technical and biological replicates?
a) To find a consensus set of peaks for downstream analysis (CORRECT)
b) To get give the best genome coverage possible
c) To reduce background noise in the data
d) To make the pipeline run faster

8. Why are mitochondrial reads removed in the nf-core/atacseq pipeline?
a) To get a better idea of the genome-wide duplication rate
b) To avoid bias in downstream analysis
c) Because some tissues and cell types can give libraries with a large fraction of mito reads
d) All of the above (CORRECT)


Extra

9. Why should you detach Nextflow from your terminal session?
a) You shouldn’t run tasks on the cluster head node
b) In case your internet connection breaks (CORRECT)
c) Jobs must be submitted from compute nodes
d) Because your laptop won’t be fast enough to use Nextflow

10. Which software packaging method is not fully reproducible?
a) Conda (CORRECT)
b) Docker
c) Singularity
d) All of the above

11. How many total members are there on the nf-core Slack workspace?
a) 110
b) 502
c) 991 (CORRECT)
d) 83