---
title: "Test yourself 03"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


Rate your confidence of being able to answer the below questions saying A, B or C, where:

- A. I am confident that I know the answer to this question
- B. I know at least 50% of the answer to this question, within 20 minutes I could find the required resources to enable a complete answer
- C. I am not confident that I can answer the question at this time.


### Part I

1. Could you identify two internal normalization methods for traditional ChIP-Seq datasets?
2. Could you identify sources of background in ChIP-Seq?
3. Could you explain the underlying assumption of comparisons relying on internal ChIP-Seq normalization?
4. Could you explain how a drug treatment can change a histone PTM landscape?
5. Could you identify factors that should should theoretically have no background in ChIP-Seq?
6. Could you explain how Drosophila spike-in is used for normalization?
7. Could you explain how is it possible to assign reads to their sample when performing multiplexed ChIP?
8. Could you identify ChIP-Seq alternatives for profiling TF binding?

### Part II

1. Could you identify two internal normalization methods for traditional ChIP-Seq datasets?
a) RPKM (correct)
b) RPGC (correct)
c) TPM (incorrect, used for RNA-Seq)
d) division by input (incorrect, this corrects for uneven input but does not ensure normalization across samples)

2. Could you identify sources of background in ChIP-Seq?
a) unspecific binding of DNA to the surface of beads
b) chromatin fragments sticking together or remaining connected via crosslinks after sonication
c) antibody binding other proteins with lower affinity
d) all of the above (correct)

3. What is the underlying assumption of comparisons relying on internal ChIP-Seq normalization?
a) that the background between samples is constant (correct)
b) that total reads counts of the samples are the same
c) that the peak height-to-background ratio is constant
d) that inputs of the samples are 

4. How can a drug treatment change a histone PTM landscape?
a) new peaks appear
b) existing peaks get smaller or bigger
c) the background (in between peaks) increases or decreases
d) all of the above (correct)

5. Which factors should theoretically have no background in ChIP-Seq (i.e. binary signal, either peak or nothing)
a) DNA specific binding factors (correct)
b) RNA Polymerase
c) Chromatin remodelers
d) Lamin

6. How is Drosophila spike-in used for normalization?
a) each dataset is scaled so that all datasets match the same absolute spike-in read count (correct)
b) all datasets are pooled and and then normalized
c) each dataset is divided by its input
d) none of the above

7. How is it possible to assign reads to their sample when performing multiplexed ChIP (BarChIP, Mint-ChIP, MINUTE-ChIP)?
a) a DNA barcode is ligated onto chromatin fragments
b) proteins are tagged before pooling
c) barcoded RNA is added to each sample
d) IPs are performed separately

8. Could you identify ChIP-Seq alternatives for profiling TF binding?
a) CUT&Run, CUT&TAG, DamID (correct)
b) only CUT&Tag and CUT&Tag
c) CUT&RUN, CUT&Tag, DamID and ATAC-seq 
d) none of the above